# justfile

build-android:
    #!/usr/bin/env bash
    echo "Building for aarch64-linux-android..."
    cargo ndk -t arm64-v8a build --release
    echo "Build completed successfully!"

clean-build-android:
    cargo clean
    just build-android

lint:
    cargo clippy --target aarch64-linux-android -- -D warnings